name: 'unit'

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

concurrency:
  group: '${{github.workflow}}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit:
    name: 'unit'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'

    - uses: 'actions/setup-node@v2'
      with:
        node-version: '12.x'

    - run: npm --version
    - run: node --version

    - name: 'npm build'
      run: 'npm ci && npm run build'

    - name: 'verify compiled'
      shell: 'bash'
      run: |-
        if [ -n "$(git status --porcelain)" ]; then
          echo "TypeScript is not compiled!"
          git diff
          exit 1
        fi
